### ISSUE TITLE
change Kind 

### ISSUE THREAD

**Issue by vadimtk** [Percona-Lab/percona-xtradb-cluster-operator#2]
change Kind to "PerconaXtraDBCluster"
https://github.com/Percona-Lab/percona-xtradb-cluster-operator/blob/31a80d6b99eab82b4a61a330d5e0413239dd79d4/config/config.yaml#L2

**Comment by dAdAbird** [comment]
Fixed: https://github.com/Percona-Lab/percona-xtradb-cluster-operator/pull/3/commits/4917851facdc6524c22a452f5449355c8464de2f
